#!/usr/bin/env bash
set -euo pipefail

# Sets TRMNL plugin config files back to production URLs.
# Usage: PROD_DOMAIN=chess.example.com scripts/restore-prod-config.sh

PROD_DOMAIN="${PROD_DOMAIN:-chess.example.com}"
BACKEND_URL="https://${PROD_DOMAIN}"
API_URL="${BACKEND_URL}/api/trmnl-state"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cat > "${ROOT_DIR}/trmnl_chess/src/settings.yml" <<EOF
#
# Changes to this file will be overwritten by \`trmnlp pull\`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
# PRODUCTION CONFIGURATION
# This file is configured for production deployment on Vercel
# For local development, use .trmnlp.yml (auto-generated by dev.sh)
#
---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: '${API_URL}'
polling_headers: ''
name: trmnl Chess
refresh_interval: 15
custom_fields:
  - keyname: backend_url
    name: Backend URL
    field_type: url
    required: true
    default: '${BACKEND_URL}'
EOF

cat > "${ROOT_DIR}/trmnl_chess/.trmnlp.yml" <<EOF
# TRMNLP configuration
---
watch:
  - .trmnlp.yml
  - src

polling_url: ${API_URL}

custom_fields:
  backend_url: ${BACKEND_URL}

variables:
  trmnl: {}
  backend_url: ${BACKEND_URL}
EOF

echo "✅ Restored production TRMNL config to ${PROD_DOMAIN}"
